### ISSUE TITLE
how to install?

### ISSUE THREAD

**Issue by toolslive** [ocamllabs/reagents#17]
```
    opam install reagents
```
I can't seem to find the package. Which ocaml do I have to switch opam to? (`opam switch <what>`)
compiling from the repo doesn't seem to work either (depends on `kcas` which I can't seem to install neither). 
help appreciated.

**Comment by kayceesrk** [comment]
You need to be on the multicore OCaml compiler to install reagents. 

```
$ opam remote add multicore https://github.com/ocamllabs/multicore-opam.git
$ opam switch 4.02.2+multicore
$ opam install reagents
```

Updated the [installation instructions](https://github.com/ocamllabs/reagents/blob/master/README.md#installation).
